"""
Fuzzy Cypher Query Corrector
============================

This module provides functions to apply fuzzy matching corrections to
Cypher queries and user questions based on reference datasets for
neighborhoods, streets, and places. It ensures that generated queries
use the correct entity names even if the user or LLM made typos.

Dependencies
------------
- os (standard library)
- re (standard library)
- pandas
- typing (standard library)
- rapidfuzz
- config.paths (providing FUZZY_DATA_DIR)

Usage
-----
Example:

    from agents.agent_cypher_rag.operations.cypher_correction import correct_cypher_query

    cypher_query = "MATCH (n:Neighborhood {name: 'Parque das Nacoes'})-[:CONTAINS]->(p:Place {type: 'pet_store'}) RETURN p"
    user_question = "Quais petshops existem no bairro Parque das Nacoes?"

    corrected_query, corrections, corrected_user_question = correct_cypher_query(
        cypher_generated=cypher_query,
        user_question=user_question
    )
"""

import os
import re
import pandas as pd
from typing import Tuple, Dict
from rapidfuzz import process, fuzz
from config.paths import FUZZY_DATA_DIR

def load_reference_data(data_dir=FUZZY_DATA_DIR) -> dict:
    """
    Load reference names from CSV files for neighborhoods, streets, and places.

    Parameters
    ----------
    data_dir : str
        Path to folder containing CSVs:
        - neighborhood_names.csv
        - street_names.csv
        - places_names.csv

    Returns
    -------
    reference_data : dict
        Dictionary of reference lists: {"neighborhood_names": [...], "street_names": [...], "places_names": [...]}
    """
    reference_data = {}
    for file in ["neighborhood_names.csv", "street_names.csv", "places_names.csv"]:
        path = os.path.join(data_dir, file)
        if os.path.exists(path):
            col_name = file.replace(".csv", "")
            df = pd.read_csv(path)
            reference_data[col_name] = df.iloc[:, 0].dropna().tolist()
    return reference_data

def fuzzy_cypher_corrector(
    cypher_query: str,
    reference_data: dict,
    threshold: int = 70
) -> Tuple[str, Dict[str, str]]:
    """
    Corrects entity names in a Cypher query using fuzzy matching against reference datasets.

    Parameters
    ----------
    cypher_query : str
        The Cypher query to correct.
    reference_data : dict
        Dictionary of reference lists to check against, e.g.,
        {"neighborhood_names": [...], "street_names": [...], "places_names": [...]}
    threshold : int, optional
        Minimum similarity score (0-100) to consider a match valid. Default is 70.

    Returns
    -------
    cypher_corrected : str
        The corrected Cypher query.
    corrections : dict
        Dictionary of applied corrections: {original_value: corrected_value}.
    """
    corrections = {}
    cypher_corrected = cypher_query

    # Capture all words/phrases inside quotes
    for quoted_value in re.findall(r'["\'](.*?)["\']', cypher_query):
        best_match = None
        best_score = 0

        # Check against each reference list
        for names_list in reference_data.values():
            match, score, _ = process.extractOne(quoted_value, names_list, scorer=fuzz.ratio)
            if score > best_score:
                best_match = match
                best_score = score

        # Apply replacement if above threshold and different
        if best_score >= threshold and best_match != quoted_value:
            cypher_corrected = cypher_corrected.replace(f"'{quoted_value}'", f"'{best_match}'")
            cypher_corrected = cypher_corrected.replace(f'"{quoted_value}"', f'"{best_match}"')
            corrections[quoted_value] = best_match
        else:
            corrections[quoted_value] = quoted_value

    return cypher_corrected, corrections

def correct_cypher_query(
    cypher_generated: str,
    user_question: str
) -> Tuple[str, Dict[str, str], str]:
    """
    Corrects a generated Cypher query using fuzzy logic and applies corrections to the user question.

    Parameters
    ----------
    cypher_generated : str
        The Cypher query generated by the LLM.
    user_question : str
        The original user question.

    Returns
    -------
    cypher_corrected : str
        The corrected Cypher query.
    corrections : Dict[str, str]
        Dictionary mapping wrong terms to corrected terms.
    user_question_corrected : str
        User question with corrections applied.
    """
    # Load reference data internally
    reference_data = load_reference_data(FUZZY_DATA_DIR)

    # Apply fuzzy correction to the generated Cypher
    cypher_corrected, corrections = fuzzy_cypher_corrector(cypher_generated, reference_data)

    # Apply the same corrections to the user question
    user_question_corrected = user_question
    for wrong, correct in corrections.items():
        user_question_corrected = user_question_corrected.replace(wrong, correct)

    return cypher_corrected, corrections, user_question_corrected

# --------------------------------------------------------
# Test block: run only if this file is executed directly
# --------------------------------------------------------

if __name__ == "__main__":
    # Load reference data
    reference_data = load_reference_data(FUZZY_DATA_DIR)

    # Example Cypher query and user question with a typo
    cypher_query = "MATCH (n:Neighborhood {name: 'Parque das Nacoes'})-[:CONTAINS]->(p:Place {type: 'pet_store'}) RETURN p"
    user_question = "Quais petshops existem no bairro Parque das Nacoes?"

    # Apply fuzzy correction to both Cypher query and user question
    corrected_query, corrections, corrected_user_question = correct_cypher_query(
        cypher_generated=cypher_query,
        user_question=user_question
    )

    print("Original query:", cypher_query)
    print("Original user question:", user_question)
    print("Corrected query:", corrected_query)
    print("Corrected user question:", corrected_user_question)
    print("Corrections applied:", corrections)