"""
Agent State Containers
======================

This module defines the Pydantic-based state containers used for orchestrating
different agents in the Graph Navigator and Cypher pipeline. It provides
structured models to track questions, extracted nodes, expanded graph nodes,
RAG reviews, Cypher queries, and agent metadata.

Classes
-------
- MasterAgentState : Overall state container for all agents.
- CypherAgentState : State container specific to the Cypher agent.
- GraphAgentState  : State container specific to the Graph/RAG agent.

Dependencies
------------
- typing
- pydantic
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

# -----------------------------
# 1 - MasterAgentState
# -----------------------------

class MasterAgentState(BaseModel):
    """
    Master state container for the overall agent orchestration.
    
    Attributes
    ----------
    user_question : str
        Original question provided by the user.
    user_question_corrected : str
        User question after any corrections (e.g., fuzzy matching).
    metadata : dict
        General metadata and logs for orchestration and agent execution.
    final_response : str
        Final natural language answer generated for the user.
    cypher_state : Optional[CypherAgentState]
        Reference to the Cypher agent specific state.
    graph_state : Optional[GraphAgentState]
        Reference to the Graph/RAG agent specific state.
    """
    user_question: str = Field(default="")
    user_question_corrected: str = Field(default="")
    metadata: Dict[str, Any] = Field(default_factory=dict)
    final_response: str = Field(default="")
    
    cypher_state: Optional["CypherAgentState"] = Field(default=None)
    graph_state: Optional["GraphAgentState"] = Field(default=None)

# -----------------------------
# 2 - CypherAgentState
# -----------------------------

class CypherAgentState(BaseModel):
    """
    State container specific to Cypher agent.

    Attributes
    ----------
    intent_detected : list of str
        List of intentions detected for the user's question.
    matched_cyphers : list of str
        List of Cypher queries retrieved as relevant to the user's question.
    cypher_generated : str
        Cypher query generated by the LLM.
    cypher_corrected : str
        Cypher query after applying fuzzy corrections on entity names.
    cypher_corrections : dict
        Dictionary of corrections applied: {incorrect_entity: corrected_entity}.
    query_results : list of dict
        Results returned by executing the Cypher query in Neo4j.
    metadata : dict
        Metadata for logging and tracking the Cypher agent's operations.
    """
    intent_detected: List[str] = Field(default_factory=list)
    matched_cyphers: List[str] = Field(default_factory=list)
    cypher_generated: str = Field(default="")
    cypher_corrected: str = Field(default="")
    cypher_corrections: Dict[str, str] = Field(default_factory=dict)
    query_results: List[Dict[str, Any]] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

# -----------------------------
# 3 - GraphAgentState
# -----------------------------

class GraphAgentState(BaseModel):
    """
    State container specific to the Graph/RAG agent.

    Attributes
    ----------
    extracted_nodes : dict
        Nodes directly extracted from the question decomposition step.
    expanded_nodes : list of dict
        Nodes expanded from the graph (reviews, places, and other related nodes),
        typically after applying RAG or traversing relationships.
    metadata : dict
        Metadata for logging and tracking the Graph/RAG agent's operations.
    """
    extracted_nodes: Dict[str, Any] = Field(default_factory=dict)
    expanded_nodes: List[Dict[str, Any]] = Field(default_factory=list)
    rag_reviews: List[Dict[str, Any]] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)

# -----------------------------
# Necessary for Pydantic forward references
# -----------------------------
MasterAgentState.update_forward_refs()