"""
Master Agent Builder and Runner with LLM Manager
================================================

This module builds and orchestrates the Master Agent composed of:
1. RAG-enabled Cypher Agent.
2. Graph Navigator Agent.
3. Validation tools to ensure answers match the user question.

The orchestration follows a StateGraph design pattern, where each agent is 
represented as a node, and conditional edges determine the execution flow.

Execution logic:
----------------
- The Cypher Agent is executed first. If its answer is valid, the process ends.
- If Cypher fails or produces an invalid answer, the Graph Navigator Agent 
  is used as a fallback to ensure robustness.
- An answer validation tool is used to confirm whether the generated 
  responses match the user's question.

Dependencies
------------
- llm.llm_manager          : Local manager for interfacing with LLMs.
- langchain.schema         : Message types (HumanMessage, AIMessage).
- langgraph.graph          : StateGraph for defining agent flows.
- langchain.tools          : Tool wrapper for validation.
- agents.agent_orchestrator.agent_state : Pydantic-based state container.
- agents.agent_cypher_rag.rag_cypher    : RAG-enabled Cypher Agent.
- agents.agent_graph_navigator.graph_navigator : Graph Navigator Agent.
- config.env_loader        : Environment loader and Neo4j credentials.
- graph.neo4j.client       : Neo4j client for query execution.
- copy                     : Deepcopy for safe state cloning.

Usage
-----
Example:

    from agents.agent_orchestrator.build_agent import build_master_agent
    from llm.llm_manager import LLMManager
    from config.env_loader import load_env, get_neo4j_credentials
    from graph.neo4j.client import Neo4jClient
    from agents.agent_orchestrator.agent_state import MasterAgentState

    load_env()

    llm_manager = LLMManager()

    uri, user, password = get_neo4j_credentials()
    neo4j_client = Neo4jClient(uri, user, password)

    master_agent = build_master_agent(llm_manager, neo4j_client)

    initial_state = MasterAgentState(user_question="Quais os dados socieconômicos do bairro Vila Assunção?")

    final_state = master_agent.invoke(initial_state)

    print("Final answer:", final_state.get("final_response"))
"""

from copy import deepcopy
from typing import Dict
from langchain.schema import HumanMessage, AIMessage
from langgraph.graph import StateGraph
from langchain.tools import Tool
from llm.llm_manager import LLMManager
from .agent_state import MasterAgentState
from agents.agent_cypher_rag.rag_cypher import RAGCypherAgent
from agents.agent_graph_navigator.graph_navigator import GraphNavigatorAgent
from config.env_loader import load_env, get_neo4j_credentials
from graph.neo4j.client import Neo4jClient

# --------------------------
# Utility: validate answer
# --------------------------

def make_validate_answer_tool(llm_manager: LLMManager) -> Tool:
    """
    Create a validation tool bound to a specific LLMManager.

    This tool can be used to verify whether an agent's answer
    correctly addresses the user's question.

    Parameters
    ----------
    llm_manager : LLMManager
        The manager instance used to interact with the LLM.

    Returns
    -------
    Tool
        A LangChain Tool wrapping the answer validation logic.
    """
    def validate_answer_tool(question: str, answer: str) -> bool:
        """
        Evaluate if an answer correctly responds to a given question.

        Parameters
        ----------
        question : str
            The user's question.
        answer : str
            The answer generated by an agent.

        Returns
        -------
        bool
            True if the answer is correct, False otherwise.
        """
        prompt = f"""
        You are an assistant that evaluates answers.
        Question: {question}
        Answer: {answer}

        Does the answer correctly and directly respond to the question?
        Reply only with "yes" or "no".
        """
        message = HumanMessage(content=prompt)
        response: AIMessage = llm_manager.chat(messages=[message])
        return response.content.lower().strip().startswith("yes")

    return Tool(
        name="validate_answer",
        description="Checks if the LLM answer correctly responds to the user question",
        func=validate_answer_tool
    )

# --------------------
# Build Cypher Agent
# --------------------

def build_cypher_agent(llm_manager: LLMManager, neo4j_client: Neo4jClient) -> StateGraph:
    """
    Construct a StateGraph representing the RAG-enabled Cypher Agent.

    The Cypher Agent handles:
    - Detecting user intent
    - Matching existing Cypher templates
    - Generating new Cypher queries
    - Correcting malformed queries
    - Executing queries on Neo4j
    - Producing natural language answers

    Parameters
    ----------
    llm_manager : LLMManager
        LLM manager to interact with the model.
    neo4j_client : Neo4jClient
        Client to execute Cypher queries on Neo4j.

    Returns
    -------
    StateGraph
        Compiled state graph representing the Cypher agent workflow.
    """
    agent = RAGCypherAgent(llm=llm_manager, neo4j_client=neo4j_client)
    builder = StateGraph(MasterAgentState)

    # Execution nodes for the Cypher agent
    builder.add_node("detect_intention", lambda state: agent.detect_intention(state))
    builder.add_node("match_cypher", lambda state: agent.match_cypher(state))
    builder.add_node("generate_cypher", lambda state: agent.generate_cypher(state))
    builder.add_node("correct_cypher", lambda state: agent.correct_cypher(state))
    builder.add_node("run_cypher_query", lambda state: agent.run_cypher_query(state))
    builder.add_node("generate_cypher_answer", lambda state: agent.generate_cypher_answer(state))

    # Execution order
    builder.set_entry_point("detect_intention")
    builder.add_edge("detect_intention", "match_cypher")
    builder.add_edge("match_cypher", "generate_cypher")
    builder.add_edge("generate_cypher", "correct_cypher")
    builder.add_edge("correct_cypher", "run_cypher_query")
    builder.add_edge("run_cypher_query", "generate_cypher_answer")

    return builder.compile()

# -------------------
# Build Graph Agent
# -------------------

def build_graph_agent(llm_manager: LLMManager) -> StateGraph:
    """
    Construct a StateGraph representing the Graph Navigator Agent.

    The Graph Navigator Agent handles:
    - Extracting relevant nodes from the graph
    - Expanding nodes based on relationships
    - Producing natural language answers from graph data

    Parameters
    ----------
    llm_manager : LLMManager
        LLM manager to interact with the model.

    Returns
    -------
    StateGraph
        Compiled state graph representing the Graph agent workflow.
    """
    graph_agent = GraphNavigatorAgent(llm=llm_manager)
    builder = StateGraph(MasterAgentState)

    # Execution nodes
    builder.add_node("extract_nodes", lambda state: graph_agent.extract_relevant_nodes(state))
    builder.add_node(
        "expand_nodes",
        lambda state: graph_agent.expand_all_nodes(
            state,
            relation_keys={
                "Neighborhood": {"Place": "CONTAINS", "Road": "CONTAINS"},
                "Road": {"Place": "CONTAINS"},
                "Intersection": {"Intersection": "ROAD"},
                "Place": {"Intersection": "NEAR", "Review": "HAS_REVIEW"},
            }
        )
    )
    builder.add_node("generate_graph_answer", lambda state: graph_agent.generate_graph_answer(state))

    # Execution order
    builder.set_entry_point("extract_nodes")
    builder.add_edge("extract_nodes", "expand_nodes")
    builder.add_edge("expand_nodes", "generate_graph_answer")

    return builder.compile()

# --------------------
# Build Master Agent
# --------------------

def build_master_agent(llm_manager: LLMManager, neo4j_client: Neo4jClient) -> StateGraph:
    """
    Build the Master Agent combining Cypher and Graph Agents with answer validation.

    Execution Logic:
    1. Run Cypher Agent
    2. If Cypher answer is valid → END
    3. If Cypher fails → Run Graph Agent
    4. Validate Graph Agent answer → END

    Parameters
    ----------
    llm_manager : LLMManager
        LLM manager for both agents.
    neo4j_client : Neo4jClient
        Client to execute Cypher queries.

    Returns
    -------
    StateGraph
        Compiled master agent with conditional branching.
    """
    cypher_agent = build_cypher_agent(llm_manager, neo4j_client)
    graph_agent = build_graph_agent(llm_manager)
    validate_answer = make_validate_answer_tool(llm_manager)

    builder = StateGraph(MasterAgentState)

    # Node: Run Cypher Agent
    def run_cypher(state: MasterAgentState) -> dict:
        result = cypher_agent.invoke(deepcopy(state))
        return {
            "final_response": result.get("final_response", ""),
            "metadata": result.get("metadata", {}),
            "cypher_state": result.get("cypher_state", {})
        }
    builder.add_node("run_cypher", run_cypher)

    # Node: Run Graph Agent as fallback
    def run_graph(state: MasterAgentState) -> dict:
        result = graph_agent.invoke(deepcopy(state))
        return {
            "final_response": result.get("final_response", ""),
            "metadata": result.get("metadata", {}),
            "graph_state": result.get("graph_state", {})
        }
    builder.add_node("run_graph", run_graph)

    # Node: END
    builder.add_node("END", lambda state: {})

    # Conditional edge: validate Cypher answer
    def check_cypher_answer(state: MasterAgentState) -> str:
        question = state.user_question
        answer = getattr(state, "final_response", "")
        cypher_state = getattr(state, "cypher_state", None)
        query_results = getattr(cypher_state, "query_results", None) if cypher_state else None
        if answer and query_results and validate_answer.func(question, answer):
            return "valid"
        return "invalid"

    builder.set_entry_point("run_cypher")
    builder.add_conditional_edges("run_cypher", check_cypher_answer, {
        "valid": "END",
        "invalid": "run_graph"
    })

    # Conditional edge: validate Graph answer
    def check_graph_answer(state: MasterAgentState) -> str:
        question = state.user_question
        answer = getattr(state, "final_response", "")
        if answer and validate_answer.func(question, answer):
            return "valid"
        return "invalid"

    builder.add_conditional_edges("run_graph", check_graph_answer, {
        "valid": "END",
        "invalid": "END"
    })

    return builder.compile()

# --------------------------------------------------------
# Test block: run only if this file is executed directly
# --------------------------------------------------------

if __name__ == "__main__":
    # Load environment variables for Neo4j and LLM
    load_env()

    # Initialize the LLM Manager
    llm_manager = LLMManager()

    # Initialize Neo4j client
    uri, user, password = get_neo4j_credentials()
    neo4j_client = Neo4jClient(uri, user, password)

    # Build master agent
    master_agent = build_master_agent(llm_manager, neo4j_client)

    # Example state
    initial_state = MasterAgentState(user_question="Quais os dados socieconômicos do bairro Vila Assunção?")
    final_state = master_agent.invoke(initial_state)

    # Extract results
    cypher_state = final_state.get("cypher_state")
    graph_state = final_state.get("graph_state")
    final_answer = final_state.get("final_response", None)

    # Display outputs
    if cypher_state and getattr(cypher_state, "query_results", None):
        print("\n=== Cypher Agent Response ===")
        print("Detected Intention:", getattr(cypher_state, "intent_detected", None))
        print("Matched Cyphers:", getattr(cypher_state, "matched_cyphers", None))
        print("Generated Cypher:", getattr(cypher_state, "cypher_generated", None))
        print("Corrected Cypher:", getattr(cypher_state, "cypher_corrected", None))
        print("Corrections Applied:", getattr(cypher_state, "cypher_corrections", None))
        print("Query Results:", getattr(cypher_state, "query_results", None))
        print("Final Answer:", final_answer)
    elif graph_state:
        print("\n=== Graph Agent Response (Fallback) ===")
        print("Expanded Nodes:", getattr(graph_state, "expanded_nodes", None))
        print("RAG Reviews:", getattr(graph_state, "rag_reviews", None))
        print("Final Answer:", final_answer)
    else:
        print("\nNo agent generated a reliable answer.")
        print("Final Answer:", final_answer)